# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d6b94d39e5e2c661d4af300ca0b52d46d9247ee9d3a440aa103476ad386f4c236638a5dd46b0bfa0f8a853946497a16c2b0fa2e836eb030758c0927f2b8ae2b0

test:
  secret_key_base: bae3f9b0170b5a84259119cc8338bcf52984862f7feaef2bbcc6803c3f546a712c1813db2354c704345c9aa6eca5c248af7f2dceaa384a90e428cec09921002f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
